# Generated by Django 4.2 on 2025-09-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('10th', '10th'), ('12th', '12th'), ('UG', 'UG'), ('PG', 'PG')], default='UG', max_length=8)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=64)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('future_paths', models.JSONField(blank=True, default=list)),
                ('jobs', models.JSONField(blank=True, default=list)),
                ('mentors', models.JSONField(blank=True, default=list)),
                ('lecture_platforms', models.JSONField(blank=True, default=list)),
                ('example_queries', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('stage', models.CharField(blank=True, max_length=8)),
                ('awaiting_specialty', models.BooleanField(default=False)),
                ('last_user_message', models.TextField(blank=True)),
                ('last_bot_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.career')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conversationsession')),
            ],
        ),
    ]
