# Generated by Django 4.2 on 2025-09-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('expertise', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='career',
            name='intelligence_layer',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='career',
            name='mentor_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='last_user_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='stage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
